### ISSUE TITLE
요구 사항 분석 git 으로 버전 관리 제안

### ISSUE THREAD

**Issue by mtak0235** [belljun3395/WifiConnectObserverAPI#23]

**Comment by mtak0235** [comment]
# 상황
#1 을 읽던 중, 요구사항 1에서 2로 넘어갈 때, 변경지점에서 명시해 놓은 것 이외에 다른 변경 지점이 있는것을 보았습니다.  그래서 요구사항 1과 번갈아 보며 달라진 점을 찾는데 리소스 사용이 있었습니다.

# 원인 분석
내용에서 달라진 부분이 가시적으로 보이지 않았기 떄문이라고 생각합니다.

# 제안
마크다운으로 작성하신 것 같은데, 레파지에서 git으로 버전 관리를 해보면 어떨까요?
커밋 때 이슈 번호를 붙여서 링킹하는 형식으로요!

**Comment by belljun3395** [comment]
저도 git으로 관리하는 것은 찬성합니다!

다만 바로 레파지에서 문서를 관리하려면 저희가 조금 더 신경써야 할 부분이 많아질 것 같아요!
<img width="1317" alt="스크린샷 2023-03-17 오전 11 02 15" src="https://user-images.githubusercontent.com/102807742/225793192-e86c48f3-1dda-4067-a6df-8f35509a78d2.png">

사진은 다른 프로젝트 깃 커밋 로그인데
커밋을 보는 것이 기능을 어떻게 개발했는가를 확인하려 보는 것인데 
문서 커밋 때문에 가독성이 안좋아질 수도 있을 것 같다라는 생각을 했어요

그래서 이번에는 우선 이슈로 문서를 작성해둔거에요!
이부분에 대해서는 조금 더 논의를 해봅시다!

**Comment by belljun3395** [comment]
#24 에서 논의됨
